[package]
name = "ping_graph"
version = "1.0.0"
edition = "2021"

[dependencies]
eframe = "0.29"
egui_plot = "0.29"
ping = "0.5"

[profile.release]
debug = true

[profile.shipping]
inherits = "release"
lto = "fat"
debug = false
codegen-units = 1
strip = "symbols"
panic = "abort"