[package]
name = "ping_graph"
version = "1.0.1"
edition = "2021"

[dependencies]
eframe = "0.32"
egui_plot = "0.33"
ping = "0.6"

[profile.release]
debug = true

[profile.shipping]
inherits = "release"
lto = "fat"
debug = false
codegen-units = 1
strip = "symbols"
panic = "abort"