name: Auto Tag and Release

permissions:
  contents: write

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Cargo.toml'
      - '.github/workflows/auto-tag.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    strategy:
      matrix:
        include:
          # x86_64 platforms
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          # ARM platforms
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history for proper versioning
      
      - name: Get version from Cargo.toml
        id: version
        run: |
          VERSION=$(grep '^version' Cargo.toml | cut -d '"' -f 2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Build for ${{ matrix.target }}
        run: |
          cargo build --release --target ${{ matrix.target }}
          mkdir -p release
          cp target/${{ matrix.target }}/release/ping_graph release/ping_graph-${{ matrix.target }}
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release v${{ steps.version.outputs.version }}
          body: Automated release for version ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            release/ping_graph-*
