name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-binary
          path: target/release/

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest-binary
          path: binaries/linux/
      - name: Download binaries (Windows)
        uses: actions/download-artifact@v3
        with:
          name: windows-latest-binary
          path: binaries/windows/
      - name: Download binaries (macOS)
        uses: actions/download-artifact@v3
        with:
          name: macos-latest-binary
          path: binaries/macos/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            binaries/linux/*
            binaries/windows/*
            binaries/macos/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
